apiVersion: v1
kind: Secret
metadata:
  name: lumina-backend-secret
  namespace: lumina
type: Opaque

stringData:
  DB_HOST: "172.31.28.139"
  DB_USER: "app"
  DB_PASSWORD: "Ankit@261,"
  DB_NAME: "authapp"
  JWT_SECRET: "efb10c20a5072ff374a9b3c1903fa4aac9520cb3acd8fdf0ec4137767c77f178"
  ADMIN_EMAIL: "admin@lumina.com"
  ADMIN_PASSWORD: "Admin@123"
